"""creacion-localidad

Revision ID: 6f53ecba6d71
Revises: 9e80dd2fa474
Create Date: 2023-06-13 19:51:12.926351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f53ecba6d71'
down_revision = '9e80dd2fa474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localidad')
    # ### end Alembic commands ###
